--***************************************************************************
--*
--**  File     :  /lua/ai/SorianAirAttackBuilders.lua
--**
--**  Summary  : Default economic builders for skirmish
--**
--**  Copyright © 2005 Gas Powered Games, Inc.  All rights reserved.
--****************************************************************************

local BBTmplFile = '/lua/basetemplates.lua'
										   
local BuildingTmpl = 'BuildingTemplates'
local BaseTmpl = 'BaseTemplates'
local ExBaseTmpl = 'ExpansionBaseTemplates'
local Adj2x2Tmpl = 'Adjacency2x2'
local UCBC = '/lua/editor/UnitCountBuildConditions.lua'
local MIBC = '/lua/editor/MiscBuildConditions.lua'
local MABC = '/lua/editor/MarkerBuildConditions.lua'
local IBC = '/lua/editor/InstantBuildConditions.lua'
local OAUBC = '/lua/editor/OtherArmyUnitCountBuildConditions.lua'
local EBC = '/lua/editor/EconomyBuildConditions.lua'
local TBC = '/lua/editor/ThreatBuildConditions.lua'
local PCBC = '/lua/editor/PlatoonCountBuildConditions.lua'
local SAI = '/lua/ScenarioPlatoonAI.lua'
local PlatoonFile = '/lua/platoon.lua'
local SBC = '/mods/Sorian Edit/lua/editor/SorianEditBuildConditions.lua'
local SIBC = '/lua/editor/SorianInstantBuildConditions.lua'

local SUtils = import('/mods/Sorian Edit/lua/AI/SorianEditutilities.lua')
local BasePanicZone, BaseMilitaryZone, BaseEnemyZone = import('/mods/AI-Uveso/lua/AI/AITargetManager.lua').GetDangerZoneRadii()

	do
	LOG('--------------------- SorianEdit Air attack Builders loading')
	end

local AirAttackPrio = function(self, aiBrain)
	local ratio = aiBrain.MyAirRatio
	local Prio1 = self.Priority
	local Prio2 = 0
	
	-- LOG('*AI DEBUG: --------------  Grabbing Air ratio, its: '..ratio..'!')
	
	if ratio < 1.0 then
	-- LOG('*AI DEBUG: --------------  Air Attack Prio Function returned false, 0')
		return 0, false
	else
		Prio2 = Prio1 * ratio
	-- LOG('*AI DEBUG: --------------  Air Attack Prio returned true, its: '..Prio2..'!')
		return Prio2, true
	end
end

local AirClaimPrio = function(self, aiBrain)
	local ratio = aiBrain.MyAirRatio
	local Prio1 = self.Priority
	local Prio2 = 0
	
	-- LOG('*AI DEBUG: --------------  Grabbing Air ratio, its: '..ratio..'!')
	
	if ratio > 1.5 then
	-- LOG('*AI DEBUG: --------------  Air Claim Prio Function returned false, We own the skies')
		return 0, false
	else
		Prio2 = Prio1 * 20
	-- LOG('*AI DEBUG: --------------  Air Claim Prio returned true, its: '..Prio2..', We really dont own the skies!')
		return Prio2, true
	end
end

BuilderGroup {
    BuilderGroupName = 'SorianEditT1AirFactoryBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
	BuilderName = 'SorianEditT1 Air Bomber Initial',
        PlatoonTemplate = 'T1AirBomber',
        Priority = 1500000,
        -- PriorityFunction = AirAttackPrio,
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ UCBC, 'LessThanGameTimeSeconds', { 380 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.4 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 2, 'BOMBER' }},
        },
        BuilderType = 'Air',
        PlatoonAddFunctions = { {SAI, 'BuildOnce'}, },
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Bomber',
        PlatoonTemplate = 'T1AirBomber',
        Priority = 1200,
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ UCBC, 'LessThanGameTimeSeconds', { 180 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.1, 0.6 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.6, 0.8 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ UCBC, 'LessThanGameTimeSeconds', { 240 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 12, 'BOMBER' }},
            { UCBC, 'HaveGreaterThanUnitsWithCategory', { 10, categories.AIR * categories.ANTIAIR} },
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 20, 'BOMBER TECH1' }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Bomber4',
        PlatoonTemplate = 'T1AirBomber',
        Priority = 900,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ UCBC, 'LessThanGameTimeSeconds', { 180 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.1, 0.6 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.6, 0.8 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { UCBC, 'HaveGreaterThanUnitsWithCategory', { 10, categories.AIR * categories.ANTIAIR} },
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 40, 'BOMBER TECH1' }},
        },
    },
    Builder {
        BuilderName = 'SorianEditT1Gunship',
        PlatoonTemplate = 'T1Gunship',
        Priority = 1100,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.1, 0.6 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.6, 0.8 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { UCBC, 'HaveGreaterThanUnitsWithCategory', { 20, categories.AIR * categories.ANTIAIR} },
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 20, 'GROUNDATTACK TECH1' }},
        },
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Fighter init',
        PlatoonTemplate = 'T1AirFighter',
        Priority = 4500,
        BuilderConditions = {
			{ UCBC, 'LessThanGameTimeSeconds', { 180 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 5, categories.AIR * categories.ANTIAIR} },
            { UCBC, 'UnitCapCheckLess', { 0.45 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Fighter',
        PlatoonTemplate = 'T1AirFighter',
        Priority = 5500,
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.4 } },
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH2 AIR' }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 20, categories.AIR * categories.ANTIAIR * categories.TECH1 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Fighter',
        PlatoonTemplate = 'T1AirFighter',
        Priority = 550000,
        BuilderConditions = {
			{ UCBC, 'LessThanGameTimeSeconds', { 280 } },
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH2 AIR' }},
            { UCBC, 'HaveLessThanUnitsWithCategory', { 3, categories.AIR * categories.ANTIAIR * categories.TECH1 } },
        },
        BuilderType = 'Air',
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditT1AntiAirBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
        BuilderName = 'SorianEditT1 Interceptors',
        PlatoonTemplate = 'T1AirFighter',
        Priority = 900,
        PriorityFunction = AirClaimPrio,
        BuilderConditions = {
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 30, categories.AIR * categories.ANTIAIR * categories.TECH1 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH2' }},
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.6, 0.7 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT1 Interceptors - Enemy Air Extra',
        PlatoonTemplate = 'T1AirFighter',
        Priority = 560,
        PriorityFunction = AirClaimPrio,
        BuilderConditions = {
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 40, categories.AIR * categories.ANTIAIR * categories.TECH1 } },
            { UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 19, categories.MOBILE * categories.AIR - categories.SCOUT, 'Enemy'}},
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 3, categories.ANTIAIR * categories.AIR - categories.BOMBER } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 2, 'FACTORY TECH2' }},
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.6, 0.7 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
        },
        BuilderType = 'Air',
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditT2AirFactoryBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
        BuilderName = 'SorianEditT2FighterBomber',
        PlatoonTemplate = 'T2FighterBomber',
        Priority = 55000000,
        BuilderType = 'Air',
        BuilderConditions = {
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH3' }},
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.4 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.75, 0.9 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
        },
    },
    Builder {
        BuilderName = 'SorianEditT2 Air Gunship',
        PlatoonTemplate = 'T2AirGunship',
        Priority = 180000,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.1, 0.6 } },
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH3' }},
            { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE GROUNDATTACK TECH2' } },
        },
    },
    Builder {
        BuilderName = 'SorianEditT2FighterBomberAdept',
        PlatoonTemplate = 'T2FighterBomber',
        Priority = 55000000,
        BuilderType = 'Air',
        BuilderConditions = {
			{ UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 15, categories.AIR * categories.MOBILE, 'Enemy'}},
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.06, 0.6 } },
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH3' }},
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.65, 0.9 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
        },
    },
    Builder {
        BuilderName = 'SorianEditT2 Air Gunship2',
        PlatoonTemplate = 'T2AirGunship',
        Priority = 1700,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { SBC, 'HaveUnitRatioSorian', { 0.5, categories.AIR * categories.GROUNDATTACK * categories.MOBILE, '<=', categories.AIR * categories.ANTIAIR * categories.MOBILE}},
        },
    },
    Builder {
        BuilderName = 'SorianEditT2 Torpedo Bomber',
        PlatoonTemplate = 'T2AirTorpedoBomber',
        Priority = 1600,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.12, 0.6 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.75, 0.9 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 20, categories.AIR * categories.ANTINAVY * categories.TECH2 } },
            --{ UCBC, 'FactoryGreaterAtLocation', { 'LocationType', 0, categories.FACTORY * categories.AIR * categories.TECH2 } },
            { TBC, 'EnemyThreatGreaterThanValueAtBase', { 'LocationType', 256, 'Naval' } },
        },
    },
    Builder {
        BuilderName = 'SorianEditT2 Torpedo Bomber ACUInWater',
        PlatoonTemplate = 'T2AirTorpedoBomber',
        Priority = 16000000,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.06, 0.6 } },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ SBC, 'IsEnemyACUInWater', {} },
        },
    }
}

BuilderGroup {
    BuilderGroupName = 'SorianEditT2AntiAirBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
        BuilderName = 'SorianEditT2AntiAirPlanes Initial Higher Pri',
        PlatoonTemplate = 'T2FighterBomber',
        Priority = 4700,
        PriorityFunction = AirClaimPrio,
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.12, 0.6 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.75, 0.9 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 4, 'FACTORY TECH3 AIR' }},
            { UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH3' }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT2AntiAirPlanes - Enemy Air',
        PlatoonTemplate = 'T2FighterBomber',
        Priority = 1700000,
        BuilderConditions = {
            { SBC, 'HaveRatioUnitsWithCategoryAndAlliance', { false, 2, categories.AIR * categories.ANTIAIR, categories.MOBILE * categories.AIR - categories.SCOUT, 'Enemy'}},
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.75, 0.9 }},
			{ UCBC, 'FactoryLessAtLocation', { 'LocationType', 1, 'FACTORY TECH3' }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            -- -- { EBC, 'GreaterThanEconIncome', { 2, 20 } },
            --{ UCBC, 'FactoryGreaterAtLocation', { 'LocationType', 0, categories.FACTORY * categories.AIR * categories.TECH2 } },
            --{ UCBC, 'HaveLessThanUnitsWithCategory', { 4, 'FACTORY TECH3' }},
        },
        BuilderType = 'Air',
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditT3AirFactoryBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
        BuilderName = 'SorianEditT3 Air Fighter init',
        PlatoonTemplate = 'T3AirFighter',
        Priority = 35000000,
        BuilderConditions = {
            { EBC, 'GreaterThanEconStorageRatio', { 0.15, 0.8 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.65, 0.8 }},
            { UCBC, 'UnitCapCheckLess', { 0.85 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Fighter Adept',
        PlatoonTemplate = 'T3AirFighter',
        Priority = 35000001,
        BuilderConditions = {
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.8 } },
			{ UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 25, categories.AIR * categories.MOBILE, 'Enemy'}},
            { UCBC, 'UnitCapCheckLess', { 0.85 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Gunship',
        PlatoonTemplate = 'T3AirGunship',
        Priority = 35000001,
        BuilderType = 'Air',
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.15, 0.8 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.65, 0.8 }},
            { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE GROUNDATTACK TECH3' } },
            -- { SBC, 'HaveUnitRatioSorian', { 0.5, categories.AIR * categories.GROUNDATTACK * categories.MOBILE, '<=', categories.AIR * categories.ANTIAIR * categories.MOBILE}},
        },
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Gunship - Anti Navy',
        PlatoonTemplate = 'T3AirGunship',
        Priority = 4500,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.8 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
            { UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 1, categories.STRUCTURE * categories.DEFENSE * categories.ANTINAVY, 'Enemy'}},
        },
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Bomber',
        PlatoonTemplate = 'T3AirBomber',
        Priority = 35000002,
        BuilderType = 'Air',
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.15, 0.8 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.65, 0.8 }},
			{ UCBC, 'HaveForEach', { categories.ANTIAIR * categories.AIR * categories.TECH3, 0.2, categories.BOMBER * categories.AIR * categories.TECH3}},
        },
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Bomber - Exp Response',
        PlatoonTemplate = 'T3AirBomber',
        Priority = 35000002,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 1, categories.TECH3 * categories.AIR * categories.BOMBER } },
            { SBC, 'T4ThreatExists', {{'Land', 'Naval', 'Structure'}, (categories.LAND + categories.NAVAL + categories.STRUCTURE + categories.ARTILLERY)}},
        },
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Bomber - Stomp Enemy',
        PlatoonTemplate = 'T3AirBomber',
        Priority = 4400,
        PriorityFunction = AirAttackPrio,
        BuilderType = 'Air',
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.15, 0.8 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.65, 0.8 }},
            { UCBC, 'HaveUnitsWithCategoryAndAlliance', { false, 6, categories.MOBILE * categories.AIR - categories.SCOUT, 'Enemy'}},
            { SBC, 'LessThanThreatAtEnemyBase', { 'AntiAir', 54 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Fighter',
        PlatoonTemplate = 'T3AirFighter',
        Priority = 4500,
        PriorityFunction = AirClaimPrio,
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.7 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.8, 1.0 }},
            -- -- { EBC, 'GreaterThanEconIncome', { 2, 20 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3 Torpedo Bomber',
        PlatoonTemplate = 'T3TorpedoBomber',
        Priority = 230000,
        BuilderType = 'Air',
        BuilderConditions = {
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.7 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.8, 1.0 }},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 4, categories.MOBILE * categories.NAVAL * categories.SUBMERSIBLE, 'Enemy'}},
        },
    },
    Builder {
        BuilderName = 'SorianEditT3 Torpedo Bomber ACUInWater',
        PlatoonTemplate = 'T3TorpedoBomber',
        Priority = 2300000000,
        BuilderType = 'Air',
        BuilderConditions = {
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.06, 0.6 } },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ SBC, 'IsEnemyACUInWater', {} },
        },
    }
}

BuilderGroup {
    BuilderGroupName = 'SorianEditT3AntiAirBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
        BuilderName = 'SorianEditT3AntiAirPlanes Initial',
        PlatoonTemplate = 'T3AirFighter',
        Priority = 2600,
        PriorityFunction = AirClaimPrio,
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.7 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.8, 1.0 }},
            -- -- { EBC, 'GreaterThanEconIncome', { 2, 20 } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3AntiAirPlanes - Enemy Air',
        PlatoonTemplate = 'T3AirFighter',
        Priority = 2300,
        PriorityFunction = AirClaimPrio,
        BuilderConditions = {
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            -- -- { EBC, 'GreaterThanEconIncome', { 2, 20 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.7 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.8, 1.0 }},
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 1, categories.ANTIAIR * categories.AIR - categories.BOMBER } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3AntiAirPlanes - Exp Response',
        PlatoonTemplate = 'T3AirFighter',
        Priority = 27000,
        BuilderConditions = {																														 
            { SBC, 'T4ThreatExists', {{'Air'}, categories.AIR}},
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.7 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
            { UCBC, 'UnitCapCheckLess', { .9 } },
        },
        BuilderType = 'Air',
    }
}

BuilderGroup {
    BuilderGroupName = 'SorianEditTransportFactoryBuilders',
    BuildersType = 'FactoryBuilder',
    Builder {
        BuilderName = 'SorianEditT1 Air Transport - Air',
        PlatoonTemplate = 'T1AirTransport',
        Priority = 2200000000,
        BuilderConditions = {
            { MIBC, 'ArmyNeedsTransports', {} },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'HaveLessThanUnitsInCategoryBeingBuilt', { 1, categories.TRANSPORTFOCUS } },
            { UCBC, 'HaveGreaterThanUnitsWithCategory', { 0, categories.MOBILE * categories.AIR * categories.ANTIAIR } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 3, categories.MOBILE * categories.AIR * categories.TECH2 }},
            { UCBC, 'PoolLessAtLocation', { 'LocationType', 3, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - categories.uea0203 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 10, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - (categories.uea0203 + categories.EXPERIMENTAL)  }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT2 Air Transport - Air',
        PlatoonTemplate = 'T2AirTransport',
        Priority = 22000,
        BuilderConditions = {
            { MIBC, 'ArmyNeedsTransports', {} },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'HaveLessThanUnitsInCategoryBeingBuilt', { 1, categories.TRANSPORTFOCUS } },
            { UCBC, 'HaveGreaterThanUnitsWithCategory', { 0, categories.MOBILE * categories.AIR * categories.ANTIAIR } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 3, categories.MOBILE * categories.AIR * categories.TECH3 }},
            { UCBC, 'PoolLessAtLocation', { 'LocationType', 3, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - categories.uea0203 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 10, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - (categories.uea0203 + categories.EXPERIMENTAL)  }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Transport - Air',
        PlatoonTemplate = 'T3AirTransport',
        Priority = 22000,
        BuilderConditions = {
            { MIBC, 'ArmyNeedsTransports', {} },
            { UCBC, 'UnitCapCheckLess', { 0.95 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'HaveLessThanUnitsInCategoryBeingBuilt', { 1, categories.TRANSPORTFOCUS } },
            { UCBC, 'HaveGreaterThanUnitsWithCategory', { 0, categories.MOBILE * categories.AIR * categories.ANTIAIR } },
            { UCBC, 'PoolLessAtLocation', { 'LocationType', 3, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - categories.uea0203 } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 10, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - (categories.uea0203 + categories.EXPERIMENTAL)  }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Transport Default - Air - init',
        PlatoonTemplate = 'T1AirTransport',
        Priority = 22000,
        BuilderConditions = {
            { UCBC, 'LessThanGameTimeSeconds', { 300 } },
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'UnitsLessAtLocation', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT1 Air Transport Default - Air',
        PlatoonTemplate = 'T1AirTransport',
        Priority = 22000,
        BuilderConditions = {
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'UnitsLessAtLocation', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 2, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - (categories.uea0203 + categories.EXPERIMENTAL)  }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT2 Air Transport Default - Air',
        PlatoonTemplate = 'T2AirTransport',
        Priority = 22000,
        BuilderConditions = {
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'UnitsLessAtLocation', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 2, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS - categories.TECH1 - categories.COMMAND - (categories.uea0203 + categories.EXPERIMENTAL)  }},
        },
        BuilderType = 'Air',
    },
    Builder {
        BuilderName = 'SorianEditT3 Air Transport Default - Air',
        PlatoonTemplate = 'T3AirTransport',
        Priority = 22000,
        BuilderConditions = {
            { EBC, 'GreaterThanEconStorageRatio', { 0.08, 0.3 } },
			{ EBC, 'GreaterThanEconTrend', { 0.0, 0.0 } },
			{ EBC, 'GreaterThanEconEfficiencyOverTime', { 0.7, 1.0 }},
            { UCBC, 'UnitsLessAtLocation', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'LocationFactoriesBuildingLess', { 'LocationType', 1, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS } },
            { UCBC, 'HaveLessThanUnitsWithCategory', { 2, categories.MOBILE * categories.AIR * categories.TRANSPORTFOCUS * categories.TECH3 - (categories.uea0203 + categories.EXPERIMENTAL)  }},
        },
        BuilderType = 'Air',
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditFrequentAirAttackFormBuilders',
    BuildersType = 'PlatoonFormBuilder',
    Builder {
        BuilderName = 'SorianEditBomberAttackT1Init',
        PlatoonTemplate = 'BomberAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 300,
        InstanceCount = 4,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 125,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 400,
            TargetSearchCategory = (categories.MOBILE * categories.ENGINEER) + (categories.STRUCTURE * categories.MASSEXTRACTION),
            PrioritizedCategories = {
                categories.ENGINEER * categories.TECH3,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH1,
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                (categories.MOBILE * categories.ENGINEER) + (categories.STRUCTURE * categories.MASSEXTRACTION),
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE BOMBER TECH1' } },
            -- { AirAttackCondition, { 'LocationType', 4 } },
            -- { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE TECH2, MOBILE AIR TECH3' } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditBomberAttackT1Frequent - Anti-Resource',
        PlatoonTemplate = 'BomberAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 201,
        InstanceCount = 3,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 125,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 400,
            TargetSearchCategory = categories.STRUCTURE * (categories.ENERGYPRODUCTION + categories.MASSEXTRACTION + categories.MASSFABRICATION),
            PrioritizedCategories = {
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.ENGINEER * categories.TECH1,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH3,
                categories.MASSEXTRACTION,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.STRUCTURE + categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.ENGINEER,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            -- { UCBC, 'HaveUnitsWithCategoryAndAlliance', { false, 4, categories.MOBILE * categories.AIR - categories.SCOUT - categories.INTELLIGENCE, 'Enemy'}},
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE BOMBER TECH1' } },
            -- { AirAttackCondition, { 'LocationType', 4 } },
            -- { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE TECH2, MOBILE AIR TECH3' } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditGunshipAttackT1',
        PlatoonTemplate = 'GunshipAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 600,
        InstanceCount = 150,
        BuilderType = 'Any',
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE GROUNDATTACK TECH1' } },
        },
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = false,
            AttackEnemyStrength = 125,
            IgnorePathing = true,
            AvoidBases = false,
            TargetSearchCategory = categories.ALLUNITS - categories.WALL - categories.TRANSPORTFOCUS,
            PrioritizedCategories = {
                categories.MASSEXTRACTION,
                categories.ENGINEER,
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.SHIELD,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
    },
    Builder {
        BuilderName = 'SorianEditTorpedoBomberComHunt',
        PlatoonTemplate = 'TorpedoBomberAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 600,
        InstanceCount = 100,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 100000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 125000,
            IgnorePathing = true,
            AvoidBases = false,
            AvoidBasesRadius = 0,
            TargetSearchCategory = categories.NAVAL + categories.COMMAND,
            PrioritizedCategories = {
                categories.COMMAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
                categories.NAVAL * (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.COMMAND,
            },
            WeaponTargetCategories = {
                categories.COMMAND,
                categories.EXPERIMENTAL,
                categories.ENGINEER,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 2, 'ANTINAVY AIR MOBILE' } },
			{ SBC, 'IsEnemyACUInWater', {} },
            -- { AirAttackCondition, { 'LocationType', 12 } },
            -- { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE TECH3' } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditTorpedoBomber',
        PlatoonTemplate = 'TorpedoBomberAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 400,
        InstanceCount = 100,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 125,
            IgnorePathing = true,
            AvoidBases = false,
            AvoidBasesRadius = 0,
            TargetSearchCategory = categories.NAVAL + categories.COMMAND,
            PrioritizedCategories = {
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
                categories.NAVAL * (categories.T1SUBMARINE + categories.T2SUBMARINE),
                categories.COMMAND,
            },
            MoveToCategories = {
                categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.ENGINEER,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 2, 'ANTINAVY AIR MOBILE' } },
            -- { AirAttackCondition, { 'LocationType', 12 } },
            -- { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE TECH3' } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditBomberAttackT2Frequent',
        PlatoonTemplate = 'BomberAttackSorianEditT2',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 400,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 125,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 400,
            TargetSearchCategory = categories.ALLUNITS - categories.WALL,
            PrioritizedCategories = {
                categories.MOBILE * categories.ANTIAIR,
                categories.MOBILE * categories.AIR,
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH3,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENGINEER * categories.TECH1,
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.STRUCTURE + categories.MOBILE + categories.COMMAND,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.ENGINEER,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE BOMBER TECH2' } },
            -- { AirAttackCondition, { 'LocationType', 12 } },
            -- { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE TECH3' } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditGunshipAttackT2Frequent',
        PlatoonTemplate = 'GunshipAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 150,
        InstanceCount = 250,
        BuilderType = 'Any',
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE GROUNDATTACK' } },
            -- { AirAttackCondition, { 'LocationType', 18 } },
            -- { UCBC, 'PoolLessAtLocation', { 'LocationType', 1, 'AIR MOBILE TECH3' } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 125,
            IgnorePathing = true,
            AvoidBases = false,
            TargetSearchCategory = categories.ALLUNITS - categories.WALL - categories.TRANSPORTFOCUS,
            PrioritizedCategories = {
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH3,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENGINEER * categories.TECH1,
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
    },
    Builder {
        BuilderName = 'SorianEditBomberAttackT3Frequent',
        PlatoonTemplate = 'BomberAttackSorianEditT3',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 100,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = true,
            AttackEnemyStrength = 2500,
            IgnorePathing = true,
            AvoidBases = false,
            AvoidBasesRadius = 0,
            TargetSearchCategory = categories.STRUCTURE + (categories.MOBILE * (categories.TECH3 + categories.COMMAND)),
            PrioritizedCategories = {
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.STRUCTURE * categories.TECH3,
                categories.MOBILE * categories.LAND * (categories.TECH2 + categories.TECH3),
                categories.STRUCTURE * categories.DEFENSE,
                categories.ENGINEER * categories.TECH3,
                categories.MASSEXTRACTION,
                categories.MOBILE * categories.LAND,
                categories.ENERGYPRODUCTION,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH1,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.STRUCTURE + (categories.MOBILE * (categories.TECH3 + categories.COMMAND)),
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.ENGINEER,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE BOMBER TECH3' } },
            -- { AirAttackCondition, { 'LocationType', 90 } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditGunshipAttackT3Frequent',
        PlatoonTemplate = 'GunshipAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        Priority = 700,
        InstanceCount = 500,
        BuilderType = 'Any',
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, 'AIR MOBILE GROUNDATTACK TECH3' } },
            -- { AirAttackCondition, { 'LocationType', 60 } },
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = false,
            AttackEnemyStrength = 250,
            IgnorePathing = true,
            AvoidBases = false,
            TargetSearchCategory = categories.ALLUNITS - categories.WALL - categories.WALL - categories.TRANSPORTFOCUS,
            PrioritizedCategories = {
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH3,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENGINEER * categories.TECH1,
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.STRUCTURE + (categories.MOBILE * (categories.TECH3 + categories.COMMAND)),
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.SHIELD,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditExpResponseFormBuilders',
    BuildersType = 'PlatoonFormBuilder',
    Builder {
        BuilderName = 'SorianEditBomberAttackExpResponse',
        PlatoonTemplate = 'BomberAttackSorianEditT23',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle' },
        Priority = 1200,
        InstanceCount = 5,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = false,
            AttackEnemyStrength = 2500,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 400,
            TargetSearchCategory = categories.EXPERIMENTAL + categories.TECH3 + categories.COMMAND,
            PrioritizedCategories = {
				categories.EXPERIMENTAL * categories.LAND,
                categories.MASSEXTRACTION,
                categories.COMMAND,
                categories.MOBILE * categories.LAND,
            },
            MoveToCategories = {
                categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.SHIELD,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            -- { UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 0, 'EXPERIMENTAL LAND, EXPERIMENTAL NAVAL', 'Enemy'}},
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 4, 'AIR MOBILE BOMBER TECH2, AIR MOBILE BOMBER TECH3' } },
            { SBC, 'T4ThreatExists', {{'Land', 'Naval', 'Structure'}, (categories.LAND + categories.NAVAL + categories.STRUCTURE + categories.ARTILLERY)}},
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditFighterAttackExpResponse',
        PlatoonTemplate = 'ThreatAirAttackSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle' },
        Priority = 1000,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 10000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = false,
            AttackEnemyStrength = 2500,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 400,
            TargetSearchCategory = categories.EXPERIMENTAL * categories.AIR,
            PrioritizedCategories = {
                categories.EXPERIMENTAL * categories.AIR,
                categories.MOBILE * categories.AIR,
            },
            MoveToCategories = {
                categories.AIR,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.COMMAND,
                categories.SHIELD,
                categories.ENERGYPRODUCTION,
                categories.ANTIAIR,
                categories.INDIRECTFIRE,
                categories.DIRECTFIRE,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            -- { UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 0, 'EXPERIMENTAL AIR', 'Enemy'}},
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 4, 'AIR MOBILE ANTIAIR TECH1, AIR MOBILE ANTIAIR TECH3' } },
            { SBC, 'T4ThreatExists', {{'Air'}, categories.AIR}},
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditMassHunterAirFormBuilders',
    BuildersType = 'PlatoonFormBuilder',
    -- Builder {
        -- BuilderName = 'SorianEditBomberAttack Mass Hunter',
        -- PlatoonTemplate = 'BomberAttackSorianEdit',
        -- -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        -- --PlatoonAddPlans = { 'AirIntelToggle', 'DistressResponseAISorian' },
        -- Priority = 100,
        -- InstanceCount = 2,
        -- BuilderType = 'Any',
        -- BuilderData = {
            -- SearchRadius = 3000,
            -- GetTargetsFromBase = false,
            -- RequireTransport = false,
            -- AggressiveMove = false,
            -- AttackEnemyStrength = 2500,
            -- IgnorePathing = true,
            -- AvoidBases = true,
            -- AvoidBasesRadius = 300,
            -- TargetSearchCategory = categories.STRUCTURE * categories.MASSEXTRACTION,
            -- PrioritizedCategories = {
                -- categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                -- categories.MASSEXTRACTION,
                -- categories.ENGINEER * categories.TECH2,
                -- categories.ENGINEER * categories.TECH3,
                -- categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                -- categories.ENGINEER * categories.TECH1,
                -- categories.ENERGYPRODUCTION,
                -- categories.STRUCTURE * categories.DEFENSE,
                -- categories.STRUCTURE,
                -- categories.MOBILE * categories.LAND,
                -- categories.NAVAL * categories.CRUISER,
                -- categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            -- },
            -- MoveToCategories = {
                -- categories.STRUCTURE * categories.MASSEXTRACTION * categories.TECH3,
                -- categories.STRUCTURE * categories.ENERGYPRODUCTION * categories.TECH3,
                -- categories.STRUCTURE * categories.MASSEXTRACTION * categories.TECH2,
                -- categories.STRUCTURE * categories.ENERGYPRODUCTION * categories.TECH2,
                -- categories.STRUCTURE * categories.MASSEXTRACTION,
                -- categories.STRUCTURE * categories.ENERGYPRODUCTION,
            -- },
            -- WeaponTargetCategories = {
                -- categories.EXPERIMENTAL,
                -- categories.ANTIAIR,
                -- categories.MASSEXTRACTION,
                -- categories.ENERGYPRODUCTION,
                -- categories.COMMAND,
                -- categories.STRUCTURE,
                -- categories.MOBILE,
            -- },
        -- },
        -- BuilderConditions = {
            -- { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 3, 'AIR MOBILE BOMBER' } },
            -- -- { AirAttackCondition, { 'LocationType', 6 } },
            -- -- { SBC, 'NoRushTimeCheck', { 0 }},
        -- },
    -- },
    -- Builder {
        -- BuilderName = 'SorianEditMass Hunter Gunships',
        -- PlatoonTemplate = 'GunshipMassHunterSorianEdit',
        -- -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        -- Priority = 950,
        -- InstanceCount = 4,
        -- BuilderConditions = {
                -- -- { UCBC, 'LessThanGameTimeSeconds', { 600 } },      
                -- -- --{ UCBC, 'HaveLessThanUnitsWithCategory', { 1, categories.TECH2 * categories.MOBILE * categories.LAND - categories.ENGINEER } },
                -- { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 3, 'AIR MOBILE GROUNDATTACK' } },
                -- -- { AirAttackCondition, { 'LocationType', 6 } },
                -- -- { SBC, 'NoRushTimeCheck', { 0 }},
            -- },
        -- BuilderData = {
            -- SearchRadius = 3000,
            -- GetTargetsFromBase = false,
            -- RequireTransport = false,
            -- AggressiveMove = false,
            -- AttackEnemyStrength = 2500,
            -- IgnorePathing = true,
            -- AvoidBases = false,
            -- AvoidBasesRadius = 300,
            -- TargetSearchCategory = categories.MASSEXTRACTION * categories.STRUCTURE,
            -- PrioritizedCategories = {
                -- categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                -- categories.MASSEXTRACTION,
                -- categories.ENGINEER * categories.TECH2,
                -- categories.ENGINEER * categories.TECH3,
                -- categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                -- categories.ENGINEER * categories.TECH1,
                -- categories.ENERGYPRODUCTION,
                -- categories.STRUCTURE * categories.DEFENSE,
                -- categories.STRUCTURE,
                -- categories.MOBILE * categories.LAND,
                -- categories.NAVAL * categories.CRUISER,
                -- categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            -- },
            -- MoveToCategories = {
                -- categories.MASSEXTRACTION,
            -- },
            -- WeaponTargetCategories = {
                -- categories.EXPERIMENTAL,
                -- categories.ANTIAIR,
                -- categories.BOMBER,
                -- categories.MOBILE,
                -- categories.ALLUNITS,
            -- },
        -- },			  
        -- BuilderType = 'Any',
    -- },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditBaseGuardAirFormBuilders',
    BuildersType = 'PlatoonFormBuilder',
    Builder {
        BuilderName = 'SorianEditAntiAirHunt',
        PlatoonTemplate = 'AntiAirHuntSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle' },
        Priority = 640,
        InstanceCount = 1500,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 3000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = false,
            AttackEnemyStrength = 2500,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 300,
            TargetSearchCategory = (categories.AIR * categories.MOBILE) + categories.STRUCTURE,
            PrioritizedCategories = {
                categories.AIR * categories.MOBILE * categories.BOMBER,
                categories.AIR * categories.MOBILE * categories.ANTIAIR * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH3,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENGINEER * categories.TECH1,
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.ANTIAIR,
                categories.BOMBER,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 0, categories.AIR * categories.MOBILE * categories.ANTIAIR - categories.TRANSPORTFOCUS - categories.EXPERIMENTAL } },
            -- { SBC, 'HaveEnoughAir', {}},
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
    Builder {
        BuilderName = 'SorianEditAntiAirBaseGuard',
        PlatoonTemplate = 'AntiAirBaseGuardSorianEdit',
        -- PlatoonAddBehaviors = { 'AirUnitRefitSorian' },
        --PlatoonAddPlans = { 'AirIntelToggle' },
        Priority = 200,
        InstanceCount = 1500,
        BuilderType = 'Any',
        BuilderData = {
            SearchRadius = 3000,
            GetTargetsFromBase = false,
            RequireTransport = false,
            AggressiveMove = false,
            AttackEnemyStrength = 2500,
            IgnorePathing = true,
            AvoidBases = true,
            AvoidBasesRadius = 300,
            TargetSearchCategory = categories.AIR * categories.MOBILE,
            PrioritizedCategories = {
                categories.MASSEXTRACTION * (categories.TECH2 + categories.TECH3),
                categories.MASSEXTRACTION,
                categories.ENGINEER * categories.TECH2,
                categories.ENGINEER * categories.TECH3,
                categories.ENERGYPRODUCTION * (categories.TECH2 + categories.TECH3),
                categories.ENGINEER * categories.TECH1,
                categories.ENERGYPRODUCTION,
                categories.STRUCTURE * categories.DEFENSE,
                categories.STRUCTURE,
                categories.MOBILE * categories.LAND,
                categories.NAVAL * categories.CRUISER,
                categories.NAVAL - (categories.T1SUBMARINE + categories.T2SUBMARINE),
            },
            MoveToCategories = {
                categories.MOBILE,
            },
            WeaponTargetCategories = {
                categories.EXPERIMENTAL,
                categories.ANTIAIR,
                categories.BOMBER,
                categories.MOBILE,
            },
        },
        BuilderConditions = {
            { UCBC, 'HaveUnitsWithCategoryAndAlliance', { true, 1, categories.AIR * categories.MOBILE * categories.ANTIAIR, 'Enemy'}},
            { UCBC, 'PoolGreaterAtLocation', { 'LocationType', 1, categories.AIR * categories.MOBILE * categories.ANTIAIR * (categories.TECH1 + categories.TECH2 + categories.TECH3) - categories.BOMBER - categories.TRANSPORTFOCUS - categories.EXPERIMENTAL } },
            -- { SBC, 'HaveEnoughAir', {}},
            -- { SBC, 'NoRushTimeCheck', { 0 }},
        },
    },
}

BuilderGroup {
    BuilderGroupName = 'SorianEditACUHunterAirFormBuilders',
    BuildersType = 'PlatoonFormBuilder',
}
	do
	LOG('--------------------- SorianEdit Air attack Builders loaded')
	end
